"""Synthetic binary fixtures; optional private sample check prints counts only."""
import copy
import hashlib
import os
from pathlib import Path
import struct
import tempfile
import unittest
import uuid
from unittest.mock import patch

from radmin_viewer.rpb import RpbError, dumps_rpb, loads_rpb, read_rpb, write_rpb
from radmin_viewer.storage import defaults, validate


def native_record(ident, name, *, parent=0, host="", port=0, user="", folder=False, slot=0):
    # Independent packed-layout fixture, not generated by the implementation.
    record = bytearray(6138)
    for offset, value in ((4904, host), (5104, name), (5908, user)):
        encoded = value.encode("utf-16le")
        record[offset:offset + len(encoded)] = encoded
    struct.pack_into("<I", record, 5304, port)
    struct.pack_into("<IIIBBI", record, 6112, ident, 0, parent, int(folder), 0, slot)
    return record


def native_file(records, deleted=()):
    out = bytearray.fromhex("04000000 01000000 00000000 fa170000 80000000 00000000 01")
    for start in range(0, len(records), 128):
        page = records[start:start + 128]
        out += bytes(0 if start+i in deleted else 1 for i in range(len(page)))
        out += bytes(128-len(page))
        out += b"".join(page)
    return bytes(out)


def fixture():
    return native_file([
        native_record(40, "研究", folder=True),
        native_record(8, "Lab", parent=40, folder=True, slot=1),
        native_record(99, "Machine 🙂", parent=8, host="例え.test", port=65535,
                      user="用户", slot=2),
        native_record(50, "IPv6", host="2001:db8::1", port=1, slot=3),
    ])


def book(count=1):
    return {"groups": ["Lab"], "connections": [
        dict(id=str(uuid.UUID(int=i+1)), name=f"Machine {i}", host="host.example",
             port=4899+i % 10, username="user", group="Lab") for i in range(count)]}


def semantics(data):
    return (set(data["groups"]), [tuple(c[k] for k in ("name", "host", "port", "username", "group"))
                                 for c in data["connections"]])


class RpbTests(unittest.TestCase):
    def test_independent_native_layout(self):
        data = loads_rpb(fixture())
        self.assertEqual(data["groups"], ["研究", "研究/Lab", "/"])
        first, second = data["connections"]
        self.assertEqual((first["name"], first["host"], first["port"], first["username"], first["group"]),
                         ("Machine 🙂", "例え.test", 65535, "用户", "研究/Lab"))
        self.assertEqual((second["host"], second["port"], second["group"]), ("2001:db8::1", 1, "/"))
        full = defaults()
        full.update(data)
        self.assertIs(validate(full), full)
        self.assertEqual(loads_rpb(fixture()), data)

    def test_writer_wire_offsets_and_semantics(self):
        data = book()
        raw = dumps_rpb(data)
        self.assertEqual(len(raw), 25+128+2*6138)
        self.assertEqual(raw[:25], bytes.fromhex(
            "04000000 01000000 00000000 fa170000 80000000 00000000 01"))
        self.assertEqual(raw[25:153], b"\x01\x01" + bytes(126))
        folder, conn = raw[153:6291], raw[6291:]
        self.assertEqual(struct.unpack_from("<IIIBBI", folder, 6112), (1, 0, 0, 1, 0, 0))
        self.assertEqual(struct.unpack_from("<IIIBBI", conn, 6112), (2, 0, 1, 0, 0, 1))
        self.assertEqual(struct.unpack_from("<I", conn, 5304)[0], 4899)
        self.assertTrue(conn[4904:].startswith("host.example\0".encode("utf-16le")))
        self.assertEqual(semantics(loads_rpb(raw)), semantics(data))

    def test_unicode_hierarchy_roundtrip(self):
        data = loads_rpb(fixture())
        self.assertEqual(semantics(loads_rpb(dumps_rpb(data))), semantics(data))

    def test_multiple_allocation_pages(self):
        data = book(260)
        raw = dumps_rpb(data)
        self.assertEqual(raw[25+785792:25+785792+128], b"\x01"*128)
        self.assertEqual(raw[25+2*785792:25+2*785792+128], b"\x01"*5+bytes(123))
        self.assertEqual(semantics(loads_rpb(raw)), semantics(data))

    def test_deleted_slots_are_not_imported(self):
        data = native_file([bytes([255])*6138, native_record(9, "Keep", host="host.test", port=4899)],
                           deleted=(0,))
        result = loads_rpb(data)
        self.assertEqual(len(result["connections"]), 1)
        self.assertEqual(result["connections"][0]["name"], "Keep")

    def test_empty_and_folder_only_books(self):
        for data in ({"groups": ["/"], "connections": []},
                     {"groups": ["Empty", "Empty/Child"], "connections": []}):
            self.assertEqual(semantics(loads_rpb(dumps_rpb(data))), semantics(data))

    def test_header_not_json_reg_or_other_version(self):
        for raw in (b"{}", b"REGEDIT4\n" + b"x"*100, b"\xff\xfe"+"Windows Registry Editor".encode("utf-16le"),
                    b"\x03"+fixture()[1:], fixture()[:12]+struct.pack("<I", 6137)+fixture()[16:]):
            with self.subTest(size=len(raw)), self.assertRaises(RpbError):
                loads_rpb(raw)

    def test_truncations_and_trailing_garbage(self):
        raw = fixture()
        # A complete header or a complete shorter phonebook can be valid. These
        # cuts instead violate a record boundary or the allocation-table marks.
        for length in (0, 1, 24, 26, 100, 152, 153, 154, 6290, 6291, len(raw)-1):
            with self.subTest(length=length), self.assertRaises(RpbError):
                loads_rpb(raw[:length])
        for suffix in (b"\0", bytes(128), bytes(140)):
            with self.assertRaises(RpbError):
                loads_rpb(raw+suffix)

    def test_unknown_allocation_flags_and_unbacked_slots(self):
        for offset, value in ((25, 2), (29, 1)):
            raw = bytearray(fixture())
            raw[offset] = value
            with self.assertRaises(RpbError):
                loads_rpb(bytes(raw))

    def test_invalid_strings_and_ports(self):
        base = native_record(1, "Name", host="host.test", port=4899)
        for offset, replacement in ((4904, b"a\0"*100), (5104, b"\x00\xd8\0\0"),
                                    (5304, struct.pack("<I", 65536)), (5304, bytes(4)),
                                    (4904, "bad/host\0".encode("utf-16le")),
                                    (5908, "bad\nuser\0".encode("utf-16le"))):
            record = bytearray(base)
            record[offset:offset+len(replacement)] = replacement
            with self.subTest(offset=offset), self.assertRaises(RpbError):
                loads_rpb(native_file([record]))

    def test_parent_integrity_duplicate_ids_and_ambiguous_paths(self):
        cases = [
            [native_record(1, "A", parent=9, folder=True)],
            [native_record(1, "A", parent=2, folder=True), native_record(2, "B", parent=1, folder=True)],
            [native_record(1, "A", folder=True), native_record(1, "B", folder=True)],
            [native_record(1, "A", folder=True), native_record(2, "A", folder=True)],
            [native_record(1, "A/B", folder=True)],
            [native_record(1, "C", parent=9, host="host.test", port=4899)],
            [native_record(0, "A", folder=True)],
        ]
        for records in cases:
            with self.assertRaises(RpbError):
                loads_rpb(native_file(records))

    def test_unsupported_routing_auth_and_extensions(self):
        for offset in (5308, 5508, 5708, 6108, 6116, 6130, 6134):
            record = native_record(1, "Name", host="host.test", port=4899)
            record[offset] = 1
            with self.subTest(offset=offset), self.assertRaises(RpbError):
                loads_rpb(native_file([record]))

    def test_unknown_model_fields_and_password_fail(self):
        for key in ("password", "unexpected"):
            data = book()
            data["connections"][0][key] = "secret"
            with self.assertRaises(RpbError):
                dumps_rpb(data)
        data = book()
        data["connections"][0]["port"] = True
        with self.assertRaises(RpbError):
            dumps_rpb(data)

    def test_utf16_capacity_no_truncation(self):
        for key in ("name", "host", "username"):
            data = book()
            data["connections"][0][key] = "x"*99
            self.assertEqual(loads_rpb(dumps_rpb(data))["connections"][0][key], "x"*99)
            data["connections"][0][key] = "x"*100
            with self.assertRaises(RpbError):
                dumps_rpb(data)
        data = book()
        data["connections"][0]["name"] = "🙂"*50
        with self.assertRaises(RpbError):
            dumps_rpb(data)

    def test_missing_export_parent_and_no_input_mutation(self):
        data = book()
        before = copy.deepcopy(data)
        dumps_rpb(data)
        self.assertEqual(data, before)
        data["groups"] = ["Missing/Child"]
        data["connections"][0]["group"] = "Missing/Child"
        with self.assertRaises(RpbError):
            dumps_rpb(data)
        with self.assertRaises(RpbError):
            dumps_rpb({"groups": ["/", "Lab"], "connections": []})

    def test_resource_limits(self):
        with patch("radmin_viewer.rpb.MAX_BYTES", 100):
            with self.assertRaises(RpbError):
                loads_rpb(fixture())
        with patch("radmin_viewer.rpb.MAX_SLOTS", 3):
            with self.assertRaises(RpbError):
                loads_rpb(fixture())
        data = book()
        data["connections"] *= 2
        with self.assertRaises(RpbError):
            dumps_rpb(data)

    def test_full_storage_model_and_atomic_file_api(self):
        data = defaults()
        data.update(book())
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory)/"book.rpb"
            write_rpb(path, data)
            before = path.read_bytes()
            self.assertEqual(semantics(read_rpb(path)), semantics(data))
            with patch("radmin_viewer.rpb.os.replace", side_effect=OSError("test failure")):
                with self.assertRaises(RpbError):
                    write_rpb(path, book(2))
            self.assertEqual(path.read_bytes(), before)
            self.assertEqual(list(Path(directory).iterdir()), [path])
            with self.assertRaises(RpbError):
                read_rpb(Path(directory)/"missing")

    @unittest.skipUnless(os.environ.get("RADMIN_RPB_SAMPLE"), "external phonebook validation is opt-in")
    def test_optional_external_phonebook_roundtrip(self):
        path = Path(os.environ["RADMIN_RPB_SAMPLE"])
        before = hashlib.sha256(path.read_bytes()).digest()
        data = read_rpb(path)
        # Do not include private values in assertion diagnostics or fixtures.
        self.assertTrue(semantics(loads_rpb(dumps_rpb(data))) == semantics(data))
        self.assertTrue(hashlib.sha256(path.read_bytes()).digest() == before)


if __name__ == "__main__":
    unittest.main()
